name: Docs
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[docs]"

      - name: Generate docs using Sphinx
        run: |
          sphinx-build -b dirhtml -d _build/doctrees . _build/dirhtml
