name: Docs
on:
  push:
    branches:
      - main
    tags: "*"
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[docs]"

      - name: Generate docs using Sphinx
        run: |
          cd docs
          sphinx-build -b dirhtml -d _build/doctrees . _build/dirhtml

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1.6.0
        with:
          version: "1.6"

      - name: Install Documenter.jl
        run: julia -e 'import Pkg; Pkg.add("Documenter")'

      - name: Deploy docs
        run: julia --project=docs/ docs/make.jl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
